### ISSUE TITLE
bug: Copy code functionality triggers for all blocks instead of just the clicked one

### ISSUE THREAD

**Issue by saliksik** [ztjhz/ChatGPTFreeApp#24]
I discovered an issue with the "Copy code" functionality. I have multiple blocks of code, and I intend to copy only the code that I click on. However, when I click on the "Copy code" button within one block, the "Copied!" message displays on all other blocks as well.

**Expected behavior:**

The "Copied!" message should appear only in the block that I clicked on, not in all the other blocks.

**Steps to reproduce:**

Click on a "Copy code" button within one block.
Observe that the "Copied!" message displays in all other blocks as well.

**Possible solution:**

The implementation needs to be revised to isolate the state for each block. Currently, the copied state is shared all ContentView components, causing it to trigger a re-render in all of them whenever there is a change.

**Comment by andrewc0de** [comment]
Let me confirm if I understand you correctly - the issue is that when you click on a "Copy code" button in one code block, the message "Copied!" appears in all the code blocks, but it's not actually copying the code from all the blocks, right? If that's the case, maybe it would help to update the title of the feature request to make it clearer.
